### ISSUE TITLE
Strong Consistency on update/delete/versioned checks should be reviewed for StronglyConsistent/GetOne

### ISSUE THREAD

**Issue by VTLee** [mappies/nodenamo#3]
1.0.6 introduced strong consistency of the GetOne and Find/list function. The MR did not address if routes like versioned updates, updates in general, delete, or other routes need to be updated to support strong consistency.

**Comment by mappies** [comment]
All operations that can be read consistently are updated.  Only internal read-by-id used in update() and delete() could not be made strongly consistent because they use GSI.  Converting GSI to LSI is not an option because of LSI limitations.
